### ISSUE TITLE
Icecast 2 - TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by Kezzsim** [fabioricali/StreamTitle#1]
Hi there,

This seems to be the only repo that actually _works_ with Shoutcast streams these days, [Icecast-Parser](https://github.com/ghaiklor/icecast-parser) doesn't seem to think any stream I give it has metadata. I was having a great deal of fun until I tried it with some icecast streams; that was when I started getting:
```
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at /Users/KariBarry/strayve/node_modules/stream-title/src/stream-title.js:30:32
    at tryCatcher (/Users/KariBarry/strayve/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/KariBarry/strayve/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/KariBarry/strayve/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/KariBarry/strayve/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/KariBarry/strayve/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/KariBarry/strayve/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/KariBarry/strayve/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/KariBarry/strayve/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

There's something inside the mystical ether of the URL parser here that's making it think it's completely undefined, regardless of what stream I give it or how I give it to it. Any ideas? I'd really like my program to be able to handle both _Icecast 2_ & _Shoutcast 1 /2_ streams if possible (since Traktor only outputs an ogg icecast stream)

Thanks!

**Comment by Kezzsim** [comment]
Also is this supposed to be run in a loop? It doesn't have any events associated with it - so thusfar if I want to get the current title I have to run it every second and then have a method change the value when changed, which seems to be causing quite a few _RequestError: Error: ETIMEDOUT_ problems...

**Comment by fabiorc428** [comment]
Hi Kezzsim,

I have released a patch that fix undefined listenurl.
StreamTitle do just HTTP request, then you must call it every x time.
